### Advin token: Authorization: Basic YWRtaW46YWRtaW4=  v1
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Positive test: Admin can create new user with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "verysTRongPassword33$",
  "role": "USER"
}


### Negative test: Admin cannot create new user with blank username
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 2 charateres
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "av",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

### Negative test: Admin cannot create new user with usermame 16 charateres
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "avgfgfrtiyrhnfdr",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username contains $%^&*()@# characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "$%^&*()@#",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blank password
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1991",
  "password": "",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password less than 8 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "1T_y234",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password without digits
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "E_ren_rt",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password without one lower case character
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "YTYTY_6799",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password without one upper case character
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "12345_rty",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password without one special character
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "123TYeernf",
  "role": "USER"
}



### Negative test: Admin cannot create new user with password with spaces
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "1234 T$fdf 567",
  "role": "USER"
}

### Negative test: Admin cannot create new user with role not from list "ADMIN", "USER"
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Kate_1990",
  "password": "verysTRongPassword33$",
  "role": "EDITOR"
}

### Negative test: Create user that already exist by admin
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate1998",
  "password": "verysTRongPassword33$",
  "role": "USER"
}

### Positive test: Authorized user can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTg6dmVyeXNUUm9uZ1Bhc3N3b3JkMzMk

### Positive test: Check account was created
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTg6dmVyeXNUUm9uZ1Bhc3N3b3JkMzMk



### Admin token: Authorization: Basic YWRtaW46YWRtaW4=
GET http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
