### Admin token: Authorization: Basic YWRtaW46YWRtaW4=  v2
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Positive test: Admin can create new user 1 with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Anne_1982",
  "password": "$some4Pass$",
  "role": "USER"
}

### Positive test: Admin can create new user 2 with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Anton_1922",
  "password": "$some5Pass$",
  "role": "USER"
}

### NEGATIVE test: User can not create new user with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "username": "Anne_1984",
  "password": "$some4PasS$",
  "role": "USER"
}

### Positive test: User 1 can authorizied with correct data
### Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "Anne_1982",
  "password": "$some4Pass$"
}

### Positive test: User 2 can authorizied with correct data
### Authorization: Basic QW50b25fMTkyMjokc29tZTVQYXNzJA==
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "Anton_1922",
  "password": "$some5Pass$"
}


### Negative test: User can not authorizied with incorrect data
### Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "Anne_1983",
  "password": "$some4Pass$"
}

### Negative test: User can not authorizied with blank username
### Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "",
  "password": "$some4Pass$"
}

### Negative test: User can not authorizied with blank password
### Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "Anne_1982",
  "password": ""
}

### Negative test: User can not authorizied without Authorization

POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "Anne_1982",
  "password": "$some4Pass$"
}

### Positive test: Authorized user 1 can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

### Positive test: Authorized user 2 can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic QW50b25fMTkyMjokc29tZTVQYXNzJA==

### Negative test: User can not create account without Authorization
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization:

### Positive test: Authorized user 1 can deposit money in account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "id": 1,
  "balance": 1000
}

### Positive test: Authorized user 2 can deposit money in account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW50b25fMTkyMjokc29tZTVQYXNzJA==

{
  "id": 2,
  "balance": 1000
}


### Negative test: User 2 cannot deposit money in account User 1
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW50b25fMTkyMjokc29tZTVQYXNzJA==

{
  "id": 1,
  "balance": 1000
}

### Negative test: User 2 cannot deposit money without Authorization
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json


{
  "id": 2,
  "balance": 1000
}

### Negative test: authorized user cannot deposit money into a non-existent account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "id": 12323423435554,
  "balance": 1000
}

### Negative test: authorized user cannot deposit money into a non-existent account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "id": 3,
  "balance": -100
}


### Negative test: authorized use cannot deposit more than 5000 into an account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "id": 3,
  "balance": 1000545454
}

### Negative test: authorized use cannot deposit 0 into an account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "id": 3,
  "balance": 0
}

### Positive test: Authorized user can transfer money from account id: 3 to account: 4
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 3,
  "receiverAccountId": 4,
  "amount": 500
}

### Negative test: Authorized user 1 cannot transfer money from account User 2: 2 to account: 1
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 500
}

### Negative test: Authorized user cannot transfer money from non-existent account to account: 4
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 334343356776,
  "receiverAccountId": 4,
  "amount": 500
}

### Negative test: Authorized user cannot transfer money from  account: 4 to non-existent account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 3,
  "receiverAccountId": 43436567576876,
  "amount": 500
}

### Negative test: Authorized user cannot transfer money more than 5000
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 3,
  "receiverAccountId": 4,
  "amount": 5001
}

### Negative test: authorized user cannot transfer a negative amount between accounts
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 3,
  "receiverAccountId": 4,
  "amount": -1
}

### Negative test: authorized user cannot transfer zero between accounts
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "senderAccountId": 3,
  "receiverAccountId": 4,
  "amount": 0
}






### Positive test: check user profile
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

### Positive test: Authorized user can update his Name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "name": "Anne_1982UPD"
}

### Negative test: authorized user cannot change the name to blank
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "name": ""
}

### Negative test: authorized user cannot change name less 3 characters
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "name": "qw"
}

### Negative test: athorized user cannot change the name to digits
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "name": "4354655"
}

### Negative test: athorized user cannot change the name to Cyrillic characters
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk

{
  "name": "кукуукунеенгор"
}

### Negative test:  User 2 cannot get transactions account User 1
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic QW50b25fMTkyMjokc29tZTVQYXNzJA==


### Negative test: User cannot get list of all users
GET http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic QW5uZV8xOTgyOiRzb21lNFBhc3Mk
